# Generated by Django 4.1.3 on 2023-03-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='Product_Category',
            field=models.CharField(choices=[('Mens and womens', 'Mens and Womens'), ('Electronics', 'Electronics'), ('Jewellery', 'Jewellery')], max_length=255),
        ),
    ]
